version: '2.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always

  app:
    build: .
    command: npm run dev
    ports:
      - 9000:9000
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./:/home/app/

